### ISSUE TITLE
Stucked :)

### ISSUE THREAD

**Issue by saldabdm** [happydasch/nspanel_haui#1]
Thanks for an as described very well thought out and feature rich software for nspanel Been trying too many hours to get it working but im stuck

Sending over some screenshots and config files
[hagui.zip](https://github.com/happydasch/nspanel_haui/files/12605911/hagui.zip)

**Comment by happydasch** [comment]
Great to see someone is trying this out!

I did look through the files you provided. It seems, that it stucked at connecting the client to the AppDaemon app. 

check apps.yaml: 

```
nspanel-haui:
  module: haui
```
try using:

```
nspanel-haui:
  module: nspanel_haui
```

did you install the tft file?


Btw. the app is in a very early stage. So there will be more issues, feel free to post any more issues you have.

**Comment by happydasch** [comment]
closing this, please reopen if the issue still exists
