### ISSUE TITLE
No day names by weather forecast and all the same

### ISSUE THREAD

**Issue by kliko22** [happydasch/nspanel_haui#15]
The clock and weather panel shows the entity name and not the day names. And all weather forecasts are the same

**Comment by happydasch** [comment]
Thanks for posting. I am aware of this. I just started to use the display for the first time in practice and am fixing all issues that are currently in the code. There are more small issues that will be fixed in the upcoming weeks.

**Comment by kliko22** [comment]
I look forward to the update and keep up the good work :-)

**Comment by kliko22** [comment]
Is there a way to override this probleem like joBr99? Otherwise I’ll wait for the next update.

**Comment by happydasch** [comment]
At the moment you are better of with other panel software. With the next version you could give it a try. I intend to make that version stable and useable. I will keep this issue updated.

**Comment by kliko22** [comment]
I will definitely try the new version. What I see now is exactly what I am looking for for this panel. I am currently using the lovelace UI version and it works well, but I like that you can determine your own front page and that it is more user-friendly. What I would like to see in the future is an easy way to go to the panel in notifications from Home Assistant and then see a popup. Good luck making a stable version!!

**Comment by kliko22** [comment]
maybe I can help translate it into Dutch

**Comment by happydasch** [comment]
Absolutly, go ahead and create a pull request. If you need any help, create a issue here. I'll also answer here more in detail: https://community.home-assistant.io/t/sonoff-nspanel-haui-homeassistant-ui/578570/6 to also address the notification.

**Comment by kliko22** [comment]
Hello, I have created a Pull request and I hope I did everything well. This is my first time working with Github!!

**Comment by happydasch** [comment]
There is a new release available, which fixes the forecast issue. Please open a new feature request with notifications and a simple usecase so i can add that functionality, too.
