### ISSUE TITLE
When running the panel it reboots after n minutes

### ISSUE THREAD

**Issue by happydasch** [happydasch/nspanel_haui#29]
The log contains following entries:

> 18:38:26 | [E] | [api:128] | No client connected to API. Rebooting...
> 18:38:26 | [I] | [app:125] | Forcing a reboot...

then it reboots

**Comment by happydasch** [comment]
@kliko22 did the last esphome update change anything in this?

**Comment by kliko22** [comment]
No I did have the same entries

**Comment by happydasch** [comment]
you could reinstall the device using the install.yaml file. it seems you do not include services, which makes the device reboot after a timeout. this is intended behaviour if there are no services. 
https://esphome.io/components/api.html

**Comment by happydasch** [comment]
Cannot reproduce issue
