### ISSUE TITLE
No return from sleep panel

### ISSUE THREAD

**Issue by happydasch** [happydasch/nspanel_haui#30]
> This is my first setup for the panels, but when it is on the weather panel I can't get back to my home panel?

**Comment by happydasch** [comment]
@kliko22 is this still happening?

**Comment by kliko22** [comment]
Wednesday it was still happaning, but I've put it aside for now because I'm busy with some other things. When I have time I will pick it up again and I look forward to your updates/adjustments

**Comment by happydasch** [comment]
Cannot reproduce this
